// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgJo19tWmOEkwTItiFSKU_2Mj-9pvTHE',
    appId: '1:891944236392:web:66e348d73dfdcf65a012dd',
    messagingSenderId: '891944236392',
    projectId: 'restomag-175ef',
    authDomain: 'restomag-175ef.firebaseapp.com',
    databaseURL: 'https://restomag-175ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restomag-175ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEC8bd_kcWQh5d7vMdULQ7SMvuc16PCXc',
    appId: '1:891944236392:android:c08c534706d184b1a012dd',
    messagingSenderId: '891944236392',
    projectId: 'restomag-175ef',
    databaseURL: 'https://restomag-175ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restomag-175ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHANZNtM4W0u2NxPZmCrDxoyFS8a6zlo',
    appId: '1:891944236392:ios:15dbff66779450eda012dd',
    messagingSenderId: '891944236392',
    projectId: 'restomag-175ef',
    databaseURL: 'https://restomag-175ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restomag-175ef.appspot.com',
    iosClientId: '891944236392-ojlt5v14q0070bca0m47pankmfsfrtjj.apps.googleusercontent.com',
    iosBundleId: 'hepl.gestion.restoMag',
  );
}
